### ISSUE TITLE
How to get mentions in twitter using this project? 

### ISSUE THREAD

**Issue by jmejia8** [DataPsycho/TwiliteTimeline.jl#8]
It would be interesting if the capabilities of this project are extended. I would like to create friendships, get mentions, send likes, etc.
If this project is accepting Pull Requests, I could  implement some of those features.

**Comment by MrDataPsycho** [comment]
@jmejia8  If you are interested to extend the project, much appreciated. No one have asked for the features you are interested before you so I have not worked on it for a while.

**Comment by jmejia8** [comment]
Thanks for your answer. I'll send you a PR soon.
